version: "3.9"
services:
  postgres:
    container_name: postgres-challenge
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airports